---
title: "Examples"
output: html_document
---

```{r}
knitr::opts_chunk$set(comment = "#>", message = FALSE)
```

```{r}
library(sf)
library(sfdep)
library(tidyverse)
```

```{r}
# spatial lag
xi <- 100
xj <- c(5, 40, 100, 35)
wj <- 1 / length(xj)
sum(xj * wj)

# Moran's I
x <- guerry_nb$crime_pers
nb <- guerry_nb$nb
wt <- guerry_nb$wt
global_moran(x, nb, wt)[["I"]]

x_lag <- st_lag(x, nb, wt)

lm(x_lag ~ x)

```

```{r}
st_contiguity(st_geometry(guerry))

guerry |> 
  transmute(nb = st_contiguity(geometry))
```

```{r}
nb <- st_contiguity(st_geometry(guerry))
nb[1:3]
```

```{r}
guerry_nb <- guerry_nb |> 
  mutate(nb = st_contiguity(geometry),
         wt = st_weights(nb))

pull(guerry_nb, "wt")[1:2]
```

```{r}
guerry_lag <- guerry_nb |> 
  mutate(crime_lag = st_lag(crime_pers, nb, wt))

select(guerry_lag, crime_pers, crime_lag) |> 
  slice(1:3)
```

```{r}
guerry_clusters <- guerry_lag |> 
  mutate(cluster = case_when(
  crime_pers > mean(crime_pers) & crime_lag > mean(crime_lag) ~ "HH",
  crime_pers > mean(crime_pers) & crime_lag < mean(crime_lag) ~ "HL",
  crime_pers < mean(crime_pers) & crime_lag < mean(crime_lag) ~ "LL",
  crime_pers < mean(crime_pers) & crime_lag > mean(crime_lag) ~ "LH"
  )) 

guerry_clusters |> 
  ggplot(aes(crime_pers, crime_lag, color = cluster)) +
  geom_point() +
  geom_vline(aes(xintercept = mean(crime_pers)), lty = 2) +
  geom_hline(aes(yintercept = mean(crime_lag)), lty = 2) +
  theme_minimal() 

```

```{r}
guerry_lisa <- guerry_nb |> 
  mutate(lisa = local_moran(crime_pers, nb, wt)) |> 
  unnest(lisa)
```

```{r}
guerry_lisa |> 
  st_drop_geometry() |> 
  select(last_col(11):last_col()) |> 
  glimpse()
```

```{r}
guerry_lisa |> 
  mutate(cluster = ifelse(
    p_folded_sim <= 0.05,
    as.character(mean), NA)) |> 
  ggplot(aes(fill = cluster)) +
  geom_sf(lwd = 0.2, color = "black") +
  theme_void()
```

